related_keys = {
    "Africana Studies": "africana-studies",
    "Anthropology": "anthropology",
    "Architecture and Design Studies": "architecture-and-design-studies",
    "Art History": "art-history",
    "Asian Studies": "asian-studies",
    "Biology": "biology",
    "Chemistry": "chemistry",
    "Chinese": "chinese",
    "Classics": "classics",
    "Cognitive and Brain Science": "cognitive-and-brain-science",
    "Computer Science": "computer-science",
    "Dance": "dance",
    "Development Studies": "development-studies",
    "Economics": "economics",
    "Environmental Science": "environmental-science",
    "Environmental Studies": "environmental-studies",
    "Ethnic and Diasporic Studies": "ethnic-and-diasporic-studies",
    "Film History": "film-history",
    "Filmmaking and Moving Image Arts": "filmmaking-and-moving-image-arts",
    "French": "french",
    "Games, Interactive Art, and New Genres": "new-genres-interactive-art",
    "Gender and Sexuality Studies": "gender-and-sexuality-studies",
    "Geography": "geography",
    "German": "german",
    "Greek (Ancient)": "greek",
    "Health, Science, and Society": "health-science-and-society",
    "History": "history",
    "International Studies": "international-studies",
    "Italian": "italian",
    "Japanese": "japanese",
    "Jewish Studies": "jewish-studies",
    "Modern and Classical Languages and Literatures": "languages-and-literatures",
    "Latin": "latin",
    "Latin American and Latino/a Studies": "latin-american-and-latinoa-studies",
    "Lesbian, Gay, Bisexual, and Transgender Studies": "lesbian-gay-bisexual-and-transgender-studies",
    "Literature": "literature",
    "Mathematics": "mathematics",
    "Middle Eastern and Islamic Studies": "middle-eastern-and-islamic-studies",
    "Music": "music",
    "New Genres and Interactive Art": "new-genres-interactive-art",
    "Philosophy": "philosophy",
    "Physics": "physics",
    "Political Economy": "political-economy",
    "Politics": "politics",
    "Practicum": "practicum",
    "Pre-Health Program": "pre-health-program",
    "Psychology": "psychology",
    "Public Policy": "public-policy",
    "Religion": "religion",
    "Russian": "russian",
    "Science, Technology, and Society": "science-and-mathematics",
    "Social Science": "social-science",
    "Sociology": "sociology",
    "Spanish": "spanish",
    "Theatre": "theatre",
    "Urban Studies": "urban-studies",
    "Visual and Studio Arts": "visual-and-studio-arts",
    "Writing": "writing",
}